### ISSUE TITLE
Prevent error running grunt-cloudfront

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow-javascript-tracker#426]
```
Fatal error: Cannot read property 'length' of null
TypeError: Cannot read property 'length' of null
    at Object.AWS.util.buffer.concat (/vagrant/node_modules/grunt-cloudfront/node_modules/aws-sdk/lib/util.js:114:29)
    at Request.HTTP_DONE (/vagrant/node_modules/grunt-cloudfront/node_modules/aws-sdk/lib/event_listeners.js:210:36)
    at Request.callListeners (/vagrant/node_modules/grunt-cloudfront/node_modules/aws-sdk/lib/sequential_executor.js:132:20)
    at Request.emit (/vagrant/node_modules/grunt-cloudfront/node_modules/aws-sdk/lib/sequential_executor.js:100:10)
    at Request.emitEvent (/vagrant/node_modules/grunt-cloudfront/node_modules/aws-sdk/lib/request.js:392:10)
    at IncomingMessage.onEnd (/vagrant/node_modules/grunt-cloudfront/node_modules/aws-sdk/lib/event_listeners.js:180:26)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:430:9)
```

This doesn't seem to prevent the invalidation happening.

**Comment by fblundun** [comment]
@jbeemster - this is part of the deployment process for new versions. When we deploy a new version we publish it to S3, then we invalidate the Cloudfront cache so that the next time sp.js is requested, Cloudfront looks it up fromm S3 rather than using an out of date version.

The invalidation was more important when we wrote new minor versions over old minor versions,. i.e. we would publish version 2.3.0 to /2/sp.js, overwriting version 2.2.0. We don't do that any more, so the invalidation would only really be important if you uploaded the wrong file and wanted to replace it.

I believe that when I tested this out, the invalidation was still happening correctly despite the error message above.
