### ISSUE TITLE
Vagrant up fails on Peru setup

### ISSUE THREAD

**Issue by dphiffer** [snowplow/snowplow-javascript-tracker#703]
Hello,

I tried setting up a Vagrant VM and ran into this error upon doing `vagrant up`:

```
(snip)
default: ===============
    default: INSTALLING PERU
    default: ---------------
    default: Downloading/unpacking peru
    default:   Running setup.py (path:/tmp/pip_build_root/peru/setup.py) egg_info for package peru
    default:     fastentrypoints
    default:     Traceback (most recent call last):
    default:       File "<string>", line 17, in <module>
    default:       File "/tmp/pip_build_root/peru/setup.py", line 56, in <module>
    default:         install_requires=get_install_requires(),
    default:       File "/tmp/pip_build_root/peru/setup.py", line 39, in get_install_requires
    default:         raise RuntimeError('The minimum supported Python version is 3.5.')
    default:     RuntimeError: The minimum supported Python version is 3.5.
    default:     Complete output from command python setup.py egg_info:
    default:     fastentrypoints
    default: 
    default: Traceback (most recent call last):
    default: 
    default:   File "<string>", line 17, in <module>
    default: 
    default:   File "/tmp/pip_build_root/peru/setup.py", line 56, in <module>
    default: 
    default:     install_requires=get_install_requires(),
    default: 
    default:   File "/tmp/pip_build_root/peru/setup.py", line 39, in get_install_requires
    default: 
    default:     raise RuntimeError('The minimum supported Python version is 3.5.')
    default: 
    default: RuntimeError: The minimum supported Python version is 3.5.
    default: 
    default: ----------------------------------------
    default: Cleaning up...
    default: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/peru
    default: Storing debug log for failure in /root/.pip/pip.log
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

I SSH'd in and confirmed that the Python version installed is 3.4.3.

**Comment by BenFradet** [comment]
hey @mhadam , could you have a look at the above and/or give an alternative route that doesn't rely on vagrant maybe?

**Comment by aharley-theknotww** [comment]
I was able get past that by making some edits to `vagrant/up.bash`. Seems like it's complaining about the ansible version requiring 3.5 further up. Replace everything between Installing Peru Dependencies and installing peru with: 
> add-apt-repository ppa:deadsnakes/ppa
> apt-get update
> apt-get install -y language-pack-en git unzip libyaml-dev python3.5 python3-pip python-yaml python-paramiko python-jinja2
> curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
> sudo python3.5 get-pip.py `

**Comment by paulboocock** [comment]
Closing this as we have decided to move to Docker for the tracker build setup and quickstart build guides. This should hopefully lead to a more robust and easy to maintain solution than Vagrant.
See #782 for progress.
